### ISSUE TITLE
Make package installable through Conda

### ISSUE THREAD

**Issue by sralchemab** [maxbachmann/Levenshtein#24]
Hi there,

Now that you have taken over this package, do you think you could make it installable through Conda as well, maybe publishing it in conda-forge as it was python-levenshtein before?

I would really appreciate this because it would make the package more compatible with pipelines.

Thank you very much in advance.

**Comment by maxbachmann** [comment]
I opened a request at conda forge: https://github.com/conda-forge/staged-recipes/pull/19605
