### ISSUE TITLE
ModuleNotFoundError: No module named 'Levenshtein.levenshtein_cpp'

### ISSUE THREAD

**Issue by Jeremy98-alt** [maxbachmann/Levenshtein#30]
Good morning Everyone!
I had this problem few minutes ago, why is there error?

```
PythonException: 
  An exception was thrown from the Python worker. Please see the stack trace below.
Traceback (most recent call last):
  File "<frozen zipimport>", line 262, in load_module
  File "C:\Users\Jeremy\AppData\Local\Temp\spark-bc9b7249-7b7c-45f4-bb98-bfb831cd02ea\userFiles-31251d1d-d5c1-43cc-9182-c4f18afaa741\Levenshtein.zip\Levenshtein\__init__.py", line 35, in <module>
    from Levenshtein.levenshtein_cpp import (
ModuleNotFoundError: No module named 'Levenshtein.levenshtein_cpp'
```

**Comment by maxbachmann** [comment]
How did you install the module?

**Comment by Jeremy98-alt** [comment]
I installed it inside python (and it worked), but when I wanted to insert this as .zip inside pyspark path, this returns me this thing

**Comment by Jeremy98-alt** [comment]
I tried to import the package inside aws and i got the same issue :(

**Comment by maxbachmann** [comment]
At least in case you installed using
```
pip install Levenshtein
```
This issue should not occur to the best of my knowledge.

**Comment by Jeremy98-alt** [comment]
Yeah I did it, but I had that problem.. also importing the packages inside the cloud

**Comment by maxbachmann** [comment]
Did you check whether levenshtein_cpp exists in the directory. The installation should not succeed unless it created this file. So I am unsure how you ended up with this broken build.

**Comment by talige** [comment]
我最近也遇到了这个问题并解决了；问题的原因如下
1、Levenshtein库需要依赖rapidfuzz库，需要将rapidfuzz一起打包；
2、注释掉 Lib\site-packages\Levenshtein\__init__.py文件里的
“from Levenshtein.levenshtein_cpp import (
    quickmedian,
    median,
    median_improve,
    setmedian,
    setratio,
    seqratio,
)”  这段代码

**Comment by maxbachmann** [comment]
How do you install the package? Can you try to run pip in verbose (using -vvv) and send me the output?
