### ISSUE TITLE
how to install it offline

### ISSUE THREAD

**Issue by leezp** [maxbachmann/Levenshtein#31]
how to install it offline on centos7 python3.6
![image](https://user-images.githubusercontent.com/16287528/182768502-57307159-6871-4246-a270-204ba9c697c7.png)
![image](https://user-images.githubusercontent.com/16287528/182768527-62f357fa-438c-4ee6-92fa-2fa9b82b8dfc.png)

and when i used 

`git clone https://github.com/maxbachmann/Levenshtein.git
cd Levenshtein
pip install .`

an error occured
![image](https://user-images.githubusercontent.com/16287528/182769213-722a721d-a03f-4a78-9621-87774358ba90.png)

**Comment by maxbachmann** [comment]
This is no issue with the package, but one with any package with dependencies. I guess you are looking for something like https://superuser.com/questions/1523218/how-to-install-python-packages-with-all-dependencies-offline-via-pip3

**Comment by leezp** [comment]
tks

**Comment by maxbachmann** [comment]
You probably do not have cmake installed on the system.
