### ISSUE TITLE
examples in docs do not accurately reflect usage (or are confusing)

### ISSUE THREAD

**Issue by ericsliu** [maxbachmann/Levenshtein#38]
For example, https://maxbachmann.github.io/Levenshtein/levenshtein.html#Levenshtein.ratio shows usage of `rapidfuzz` in the examples, when it should just be `Levenshtein.ratio`

In the case of https://maxbachmann.github.io/Levenshtein/levenshtein.html#distance it mentions importing `from rapidfuzz.distance import Levenshtein` which will conflict with importing this project's Levenshtein module.
While `rapidfuzz.distance.Levenshtein.distance` works, there is no `rapidfuzz.distance.Levenshtein.ratio`.

These issues seem to stem from auto-generated docs that pull from the `rapidfuzz` dependency.

**Comment by maxbachmann** [comment]
I did already see this issue, but was not completely sure how I should solve it. I could:
1) write the docs by hands for these functions
2) wrap them in a function in Levenshtein

option 2) has the advantage, that it is better for `help()` as well.

**Comment by maxbachmann** [comment]
I fixed the documentation
