### ISSUE TITLE
Typing stubs are not distributed with the package

### ISSUE THREAD

**Issue by slavfox** [maxbachmann/Levenshtein#42]
Installing the package (0.20.6) with `pip` only installs the `.py` files and the shared library. The `py.typed` marker and the `.pyi` do not get installed, and are therefore of no use to type checkers.

Output of `check_typedpkg` listed in [PEP-0561](https://peps.python.org/pep-0561/):
```console
$ python -m typed_check Levenshtein
Package Levenshtein does not support typing.
```

**Comment by maxbachmann** [comment]
Thanks for reporting. This is fixed in `v0.20.7`.
