### ISSUE TITLE
score_cutoff argument not seeming to work for ratio

### ISSUE THREAD

**Issue by ViennaMike** [maxbachmann/Levenshtein#45]
I just discovered Levenshtein and am trying it out as a hopefully faster alternative to SequenceMatcher.  I only care about high level of matches, so I tried to set the score_cutoff parameter and got an error. Here's the simple example from the documentation, running on Anaconda on Windows, with and without the parameter:

`ratio("lewenstein", "levenshtein", score_cutoff=0.9)
Traceback (most recent call last):

  File "C:\Users\mikem\AppData\Local\Temp\ipykernel_14020\1371377410.py", line 1, in <module>
    ratio("lewenstein", "levenshtein", score_cutoff=0.9)

TypeError: ratio() takes no keyword arguments

ratio("lewenstein", "levenshtein")
Out[3]: 0.8571428571428571`

Any idea why setting score_cutoff doesn't work?

**Comment by maxbachmann** [comment]
What is the version of Levenshtein you are using?

```python
import Levenshtein
print(Levenshtein.__version__)
```

**Comment by maxbachmann** [comment]
The current version is available on conda: https://anaconda.org/conda-forge/levenshtein, so you should be able to upgrade

**Comment by ViennaMike** [comment]
Thanks! I was using the packages search in Anaconda Navigator, rather than
conda-forge. I've installed the current version and it works fine.

p.s., With Levenshtein, my code seems to be running significantly faster
even without that cutoff than the quick_ratio option of SequenceMatcher,
which has my run times down to an acceptable level. And now even faster
with the cutoff.

**Comment by maxbachmann** [comment]
When processing large amounts of data you should try to use [`rapidfuzz`](https://github.com/maxbachmann/RapidFuzz) directly: 
```python
from rapidfuzz.distance import Indel
from rapidfuzz import process

process.cdist(queries, choices, scorer=Indel.normalized_similarity, score_cutoff=score_cutoff, workers=-1)
```
It saves some overhead by reducing calls into Python, uses SIMD to compare multiple sequences in parallel when possible and allows the use of multiple threads (workers argument).

**Comment by ViennaMike** [comment]
Thanks!
