### ISSUE TITLE
Module 'Levenshtein' has no attribute 'distance'

### ISSUE THREAD

**Issue by grabani** [maxbachmann/Levenshtein#51]
Running Levenshtein 0.20.9 (on Windows 11. Python 3.7.0) I get the error:

`AttributeError: module 'Levenshtein' has no attribute 'distance'`

The associated Python code is:

`import Levenshtein`

`distance1 = Levenshtein.distance(line1, line2)`

I have installed the Levenshtein package several times, rebooted my laptop.

Is my version of Python compatible with Levenshtein 0.20.9?

PS - The pypi site captures that the package is compatible with Python 3.6.0 and later versions. 

Thanks.

**Comment by maxbachmann** [comment]
Yes it should be compatible. The only case I am aware of, which leads to something like this, is an incompatible installation of an old version of `python-Levenshtein` and `Levenshtein`. This is usually resolved by:
```
pip uninstall Levenshtein python-Levenshtein
pip install Levenshtein
```
If this does not fix the issue: Can you check in your installation directory which files are installed in there for the `Levenshtein` module?

**Comment by grabani** [comment]
Unfortunately that didn't work. I also uninstalled and re-installed the `rapidfuzz` package as it contained references to the Levenshtein package.

The files in my Levenshtein package installation are:

![image](https://user-images.githubusercontent.com/25469154/224382136-02930a4d-d1bd-494c-ada7-470597600d2a.png)

![image](https://user-images.githubusercontent.com/25469154/224382272-f746d9ad-3b5a-450c-b61b-83e05bf47da0.png)

**Comment by maxbachmann** [comment]
The directory looks correct. What it the output of `dir(Levenshtein)`?

**Comment by grabani** [comment]
print(dir(Levenshtein))
['Levenshtein', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__spec__']

**Comment by maxbachmann** [comment]
Sounds to me like you are importing from somewhere incorrect. Is `Levenshtein.__path__` the expected path?

**Comment by grabani** [comment]
Sorry, how do I check if `Levenshtein.__path__` the expected path?

**Comment by maxbachmann** [comment]
You can simply print it and see whether it is the path to the site-packages directory of Levenshtein.

**Comment by grabani** [comment]
I get the following error:

 `print(Levenshtein.__path__)`
`AttributeError: module 'Levenshtein' has no attribute '__path__'`

**Comment by maxbachmann** [comment]
Ah sorry I did not see it was missing from your import. Still this means something is going horribly wrong. It is hard to tell what exactly is wrong in your environment. Maybe try to perform the same from a python shell in a different directory.

From what I can tell this is unrelated to the package itself.

**Comment by grabani** [comment]
My coding has all be done in VSCode. I will try and execute using the Python 3.7.0 command line.

**Comment by maxbachmann** [comment]
I would start off by comparing `sys.path` for the command line and the run from within VS Code.

**Comment by grabani** [comment]
For the benefit of others...

The issue was caused by the fact that my Python code file was called `Levenshtein.py`. Changing the name of my Python code file resolved the issue.

Thanks.
