### ISSUE TITLE
dependency rapidfuzz 3.0

### ISSUE THREAD

**Issue by pur80a** [maxbachmann/Levenshtein#53]
Hi, 

I just noticed when updating my pip packages, that Levenshtein required rapidfuzz >=2.3.0,<3.0.0 and rapidfuzz 3.0 is available. 
Will the next release be compatible with version 3.0? If so, do you already have estimates as to when? 

Much Thanks!

**Comment by maxbachmann** [comment]
The new release does not break any API used here. I just released a version with the relaxed version requirement, which will be available once the CI build finishes.
