### ISSUE TITLE
Make it a rust crate

### ISSUE THREAD

**Issue by G2GreenTea** [maxbachmann/Levenshtein#55]
I compared the running speed of this package with 8 crates of rust. I found that it is more than ten times faster than those crates. So I really hope to see you make a crate that can calculate levenshtein distance. 
Or do you know how to use this package in rust? I have tried using PyO3 before, but it is still not as fast as running directly in Python.

**Comment by maxbachmann** [comment]
This would require at least partially porting `rapidfuzz` to rust. I was working on this a couple of years ago in https://github.com/maxbachmann/rapidfuzz-rs, but this would basically need to be completely rewritten.

The algorithms themselves should be fairly easy to port. However I am completely unfamiliar with rust and the C++ implementation uses a couple of more advanced C++ features:
- conditional compilation using `if constexpr` to reduce code duplication (Worst case this could be duplicated in rust)
- should work for any numeric iterables not just strings. In C++ this is defined as:
```cpp
template <typename InputIt1, typename InputIt2>
double ratio(InputIt1 first1, InputIt1 last1, InputIt2 first2, InputIt2 last2, double score_cutoff = 0);
```
not sure how this would need to be implemented with rust generics to work both for strings and any other iterables of numeric items

This topic already came up a couple of months ago here: https://github.com/maxbachmann/RapidFuzz/discussions/331, but I never heard back from @bcvanmeurs again. While I am absolutely willing to work on the algorithms themselves, I think it would be good to have someone with more rust knowledge help with the API design.

**Comment by maxbachmann** [comment]
I had a look at this this evening. I will probably work on this, but it will certainly take a while to port.

**Comment by G2GreenTea** [comment]
It’s fantastic news. I am extremely grateful for your willingness to take on this task. As a beginner, I feel limited in my abilities to contribute, but I am truly appreciative of your efforts. If there’s any way I can assist or support the project, please let me know. Thank you once again for your dedication and expertise in this endeavor!

**Comment by maxbachmann** [comment]
I assume you are working with relatively large strings.

I started working on the rust rewrite in https://github.com/maxbachmann/rapidfuzz-rs/tree/rewrite. So far I have the normal Levenshtein distance pretty much fully implemented, but there are still quite a few features missing. I will probably implement a decent chunk of them, but make a release on cargo before implementing all features.

Performance of the Levenshtein implementation looks to be on par with the C++ implementation (generates largely the same assembler when compiled with llvm). Here is an initial comparision with strsim which appears to be a widely used library for string similarities in rust:

![lines2](https://github.com/maxbachmann/Levenshtein/assets/44199644/e5ed2b97-e938-42db-9323-83d193d73281)

**Comment by G2GreenTea** [comment]
Perfect! This is a huge progress. Looking forward to the release on cargo!
